[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
tic_tac_toe = "5xD2yUE3PTnb5LbcioaYtskELvJTFuBjcRfA5vmZhS8B"

[programs.devnet]
tic_tac_toe = "5xD2yUE3PTnb5LbcioaYtskELvJTFuBjcRfA5vmZhS8B"

[programs.mainnet]
tic_tac_toe = "5xD2yUE3PTnb5LbcioaYtskELvJTFuBjcRfA5vmZhS8B"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
